#pragma once
#include "include/animation.hpp"
#include "include/background.hpp"
#include "include/collision.hpp"
#include "include/death.hpp"
#include "include/drawable.hpp"
#include "include/movement.hpp"
#include "include/player.hpp"
#include "include/sound.hpp"